name: Build
on:
  push:
    branches-ignore: [main]
    paths-ignore: ['**.md', '.gitignore', 'LICENSE']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Build hera-builder-base
        run: docker build --target hera-builder-base -t hera-builder-base:testing .

      - name: Build hera-runner-base
        run: docker build --target hera-runner-base -t hera-runner-base:testing .

      - name: Run test
        working-directory: test
        run: bash run-test.sh
