name: Build
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build hera-builder
        uses: docker/build-push-action@v5
        with:
          push: false
          target: hera-builder

      - name: Build hera-runner
        uses: docker/build-push-action@v5
        with:
          push: false
          target: hera-runner
