name: Build and push
on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '.gitignore', 'LICENSE']
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: |
          date=$(date +'%Y%m%d')
          echo "date=${date}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push hera-builder
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_NAMESPACE }}/hera-builder:jammy,${{ vars.DOCKER_NAMESPACE }}/hera-builder:jammy-${{ steps.date.outputs.date }}
          target: hera-builder

      - name: Build and push hera-runner
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_NAMESPACE }}/hera-runner:jammy,${{ vars.DOCKER_NAMESPACE }}/hera-runner:jammy-${{ steps.date.outputs.date }}
          target: hera-runner
