name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Build the Docker images
        run: |
          docker build --target hera-builder -t pimhuisman/hera-builder:jammy .
          docker build --target hera-runner -t pimhuisman/hera-runner:jammy .
