name: Snyk scan
on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '.gitignore', 'LICENSE']
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '53 7 * * 3'

jobs:
  snyk:
    name: Snyk scan
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build --target hera-runner-base -t snyk/hera-runner-base .

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: snyk/hera-runner-base
          args: --file=Dockerfile

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
